/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.Product;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.FocusEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.ImageIcon;
import javax.imageio.ImageIO;

/**
 *
 * @author Bhabani
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
////    CreateJPanel() {
////    JFrame frame = new JFrame("scroll");
////    JScrollBar sBar = new JScrollBar();
////    sBar.setBounds(1000,1000,20,1000);
////    frame.add(sBar);
////    frame.setSize(900, 900);
////    frame.setLayout(null);
////    frame.setVisible(true);
////    }
//    
//    public static void main(String[] args, CreateJPanel CreateJPanel) {
//        CreateJPanel = new CreateJPanel();
//    }
    
    Product product;
    private Object lblFirstNameValidation;
    public CreateJPanel(Product product) {
        initComponents();
        this.product = product;
    }
    
    boolean isFirstName = false;
boolean isDOB = false;
boolean isLastName = false;
boolean isAddress = false;
boolean isPhNum = false;
boolean isFaxNum = false;
boolean isEmailID = false;
boolean isSSN = false;
boolean isMedRec = false;
boolean isHPBNum = false;
boolean isBnkAccNum = false;
boolean isLicNum = false;
boolean isVecType = false;
boolean isSrNum = false;
boolean isIMEINum = false;
boolean isLinkedIn = false;
boolean isIPAdd = false;
boolean isFaceRec = false;
boolean isimgUpload = false;
boolean isUniqueID = false;
boolean isIOSRadioBtn = false;
boolean isAndroidRadioButton = false;
boolean isWindowsRadioButton1 = false;
boolean isRadio = false; 



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        devType = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        vecSrNum = new javax.swing.JLabel();
        vecType = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        licNum = new javax.swing.JLabel();
        fullFaceMulPics = new javax.swing.JLabel();
        linkedIn = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        frstName = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        dob = new javax.swing.JLabel();
        phNum = new javax.swing.JLabel();
        faxNum = new javax.swing.JLabel();
        bnkAccNum = new javax.swing.JLabel();
        ssnNum = new javax.swing.JLabel();
        emailID = new javax.swing.JLabel();
        addIP = new javax.swing.JLabel();
        medRecNum = new javax.swing.JLabel();
        imeiNum = new javax.swing.JLabel();
        hlthBenNum = new javax.swing.JLabel();
        uniqueID = new javax.swing.JLabel();
        lstName = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        txtVecType = new javax.swing.JComboBox<>();
        txtIPAdd = new javax.swing.JFormattedTextField();
        txtPhNum = new javax.swing.JFormattedTextField();
        txtFaxNum = new javax.swing.JFormattedTextField();
        txtSSN = new javax.swing.JFormattedTextField();
        txtBnkAccNum = new javax.swing.JFormattedTextField();
        txtHPBNum = new javax.swing.JFormattedTextField();
        txtMedRec = new javax.swing.JFormattedTextField();
        txtLicNum = new javax.swing.JFormattedTextField();
        txtUniqueID = new javax.swing.JFormattedTextField();
        txtIMEINum = new javax.swing.JFormattedTextField();
        iOSRadioBtn = new javax.swing.JRadioButton();
        androidRadioButton = new javax.swing.JRadioButton();
        windowsRadioButton1 = new javax.swing.JRadioButton();
        txtEmailID = new javax.swing.JFormattedTextField();
        txtDOB = new com.toedter.calendar.JDateChooser();
        lblValFName = new javax.swing.JLabel();
        lblValLName = new javax.swing.JLabel();
        txtSrNum = new javax.swing.JFormattedTextField();
        lblValAdd = new javax.swing.JLabel();
        txtLinkedIn = new javax.swing.JFormattedTextField();
        uploadImg = new javax.swing.JButton();
        imgUpload = new javax.swing.JLabel();
        lblValBANum = new javax.swing.JLabel();
        lblValFaxNum = new javax.swing.JLabel();
        lblValSSNNum = new javax.swing.JLabel();
        lblValBenNum = new javax.swing.JLabel();
        lblValSrNum = new javax.swing.JLabel();
        lblValMedNum = new javax.swing.JLabel();
        lblValIMEINum = new javax.swing.JLabel();
        lblValIPAdd = new javax.swing.JLabel();
        lblEINNum = new javax.swing.JLabel();
        lblLicNum = new javax.swing.JLabel();
        lblValPhNum = new javax.swing.JLabel();
        txtLinkedIn1 = new javax.swing.JFormattedTextField();

        devType.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        devType.setText("Device Type:");

        txtFirstName.setAlignmentY(0.1F);
        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });
        txtFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFirstNameKeyTyped(evt);
            }
        });

        vecSrNum.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        vecSrNum.setText("Vehicle Serial Number:");

        vecType.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        vecType.setText("Vehicle Type:");

        txtLastName.setAlignmentY(0.1F);
        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });
        txtLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLastNameKeyTyped(evt);
            }
        });

        licNum.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        licNum.setText("Licence Number:");

        fullFaceMulPics.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        fullFaceMulPics.setText("Full Face Multiple Photos:");

        linkedIn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        linkedIn.setText("LinkedIn:");

        lblTitle.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create Profile");

        frstName.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        frstName.setText("First Name:");
        frstName.setAlignmentY(0.1F);

        address.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        address.setText("Address:");
        address.setAlignmentY(0.1F);

        dob.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        dob.setText("Date of Birth:");
        dob.setAlignmentY(0.1F);

        phNum.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        phNum.setText("Phone Number:");
        phNum.setAlignmentY(0.1F);

        faxNum.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        faxNum.setText("Fax Number:");
        faxNum.setAlignmentY(0.1F);

        bnkAccNum.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        bnkAccNum.setText("Bank account Number:");
        bnkAccNum.setAlignmentY(0.1F);

        ssnNum.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        ssnNum.setText("SSN Number:");
        ssnNum.setAlignmentY(0.1F);

        emailID.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        emailID.setText("Email ID:");
        emailID.setAlignmentY(0.1F);

        addIP.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        addIP.setText("IP Address:");

        medRecNum.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        medRecNum.setText("Medical Record Number:");

        imeiNum.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        imeiNum.setText("IMEI Number:");

        hlthBenNum.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        hlthBenNum.setText("Health plan beneficiary Number:");
        hlthBenNum.setAlignmentY(0.1F);

        uniqueID.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        uniqueID.setText("EIN Number:");

        lstName.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        lstName.setText("Last Name:");
        lstName.setAlignmentY(0.1F);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtVecType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Car", "Bike" }));
        txtVecType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVecTypeActionPerformed(evt);
            }
        });

        try {
            txtIPAdd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###.###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtIPAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIPAddActionPerformed(evt);
            }
        });
        txtIPAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIPAddKeyTyped(evt);
            }
        });

        try {
            txtPhNum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtPhNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhNumActionPerformed(evt);
            }
        });
        txtPhNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPhNumKeyTyped(evt);
            }
        });

        try {
            txtFaxNum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtFaxNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFaxNumActionPerformed(evt);
            }
        });
        txtFaxNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFaxNumKeyTyped(evt);
            }
        });

        try {
            txtSSN.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSSNActionPerformed(evt);
            }
        });
        txtSSN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSSNKeyTyped(evt);
            }
        });

        try {
            txtBnkAccNum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("############")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtBnkAccNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBnkAccNumActionPerformed(evt);
            }
        });
        txtBnkAccNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBnkAccNumKeyTyped(evt);
            }
        });

        try {
            txtHPBNum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtHPBNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHPBNumActionPerformed(evt);
            }
        });
        txtHPBNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHPBNumKeyTyped(evt);
            }
        });

        try {
            txtMedRec.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtMedRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedRecActionPerformed(evt);
            }
        });
        txtMedRec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMedRecKeyTyped(evt);
            }
        });

        try {
            txtLicNum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("AAAAAAAAA")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtLicNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLicNumActionPerformed(evt);
            }
        });
        txtLicNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLicNumKeyTyped(evt);
            }
        });

        try {
            txtUniqueID.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtUniqueID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUniqueIDActionPerformed(evt);
            }
        });
        txtUniqueID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUniqueIDKeyTyped(evt);
            }
        });

        try {
            txtIMEINum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###############")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtIMEINum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIMEINumActionPerformed(evt);
            }
        });
        txtIMEINum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIMEINumKeyTyped(evt);
            }
        });

        buttonGroup1.add(iOSRadioBtn);
        iOSRadioBtn.setText("iOS");
        iOSRadioBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        iOSRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iOSRadioBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(androidRadioButton);
        androidRadioButton.setText("Android");

        buttonGroup1.add(windowsRadioButton1);
        windowsRadioButton1.setText("Windows");

        try {
            txtEmailID.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("******************************************************")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtEmailID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailIDActionPerformed(evt);
            }
        });

        lblValFName.setForeground(new java.awt.Color(255, 51, 0));

        lblValLName.setForeground(new java.awt.Color(255, 51, 0));

        try {
            txtSrNum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("*******")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtSrNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSrNumActionPerformed(evt);
            }
        });
        txtSrNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSrNumKeyTyped(evt);
            }
        });

        lblValAdd.setForeground(new java.awt.Color(255, 51, 0));

        try {
            txtLinkedIn.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("*****************************")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtLinkedIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLinkedInActionPerformed(evt);
            }
        });

        uploadImg.setText("Browse");
        uploadImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadImgActionPerformed(evt);
            }
        });

        lblValBANum.setForeground(new java.awt.Color(255, 51, 0));

        lblValFaxNum.setForeground(new java.awt.Color(255, 51, 0));

        lblValSSNNum.setForeground(new java.awt.Color(255, 51, 0));

        lblValBenNum.setForeground(new java.awt.Color(255, 51, 0));

        lblValSrNum.setForeground(new java.awt.Color(255, 51, 0));

        lblValMedNum.setForeground(new java.awt.Color(255, 51, 0));

        lblValIMEINum.setForeground(new java.awt.Color(255, 51, 0));

        lblValIPAdd.setForeground(new java.awt.Color(255, 51, 0));

        lblEINNum.setForeground(new java.awt.Color(255, 51, 0));

        lblLicNum.setForeground(new java.awt.Color(255, 51, 0));

        lblValPhNum.setForeground(new java.awt.Color(255, 51, 0));

        try {
            txtLinkedIn1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("*****************************")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtLinkedIn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLinkedIn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(frstName)
                            .addComponent(address)
                            .addComponent(dob)
                            .addComponent(phNum)
                            .addComponent(faxNum)
                            .addComponent(bnkAccNum)
                            .addComponent(devType)
                            .addComponent(vecSrNum)
                            .addComponent(vecType)
                            .addComponent(ssnNum)
                            .addComponent(hlthBenNum)
                            .addComponent(lstName)
                            .addComponent(medRecNum)
                            .addComponent(emailID))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(txtHPBNum, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(txtMedRec, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPhNum, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFaxNum, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtBnkAccNum, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblValBenNum, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblValBANum, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblValSSNNum, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(lblValFaxNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblValFName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblValLName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblValMedNum, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblValPhNum, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(imeiNum)
                                    .addComponent(uniqueID)
                                    .addComponent(fullFaceMulPics)
                                    .addComponent(addIP)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtVecType, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(licNum))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtLinkedIn1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(linkedIn)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uploadImg)
                            .addComponent(txtIPAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIMEINum, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUniqueID, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLicNum, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(364, 364, 364)
                        .addComponent(lblValAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(441, 441, 441)
                        .addComponent(btnSave))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(txtEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(txtSrNum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblValSrNum, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(iOSRadioBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(androidRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(windowsRadioButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEINNum, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValIPAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValIMEINum, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLicNum, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(896, 896, 896)
                .addComponent(imgUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtBnkAccNum, txtDOB, txtEmailID, txtFaxNum, txtFirstName, txtHPBNum, txtLastName, txtLinkedIn1, txtMedRec, txtPhNum, txtSSN, txtSrNum, txtVecType});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtIMEINum, txtIPAdd, txtLicNum, txtLinkedIn, txtUniqueID});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblEINNum, lblLicNum, lblValIMEINum, lblValIPAdd});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblValBANum, lblValBenNum, lblValFName, lblValFaxNum, lblValLName, lblValMedNum, lblValSSNNum, lblValSrNum});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblTitle)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(frstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblValFName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValIMEINum, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(imeiNum, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtIMEINum, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(linkedIn))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(28, 28, 28)
                                    .addComponent(txtLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblValLName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(addIP, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtIPAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblValIPAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fullFaceMulPics)
                                    .addComponent(uploadImg))
                                .addGap(48, 48, 48)
                                .addComponent(uniqueID, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(licNum))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(imgUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtUniqueID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14)
                                        .addComponent(txtLicNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblEINNum, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblLicNum, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lstName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtLinkedIn1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(phNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPhNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(faxNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtFaxNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblValFaxNum, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ssnNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblValSSNNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bnkAccNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtBnkAccNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblValBANum, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblValPhNum, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(hlthBenNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtHPBNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(vecType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtVecType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblValBenNum, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(vecSrNum)
                                .addComponent(txtSrNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblValSrNum, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(medRecNum, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMedRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblValMedNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(btnSave))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(emailID)
                                    .addComponent(txtEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(devType)
                                    .addComponent(iOSRadioBtn)
                                    .addComponent(androidRadioButton)
                                    .addComponent(windowsRadioButton1))))
                        .addContainerGap(12, Short.MAX_VALUE))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtBnkAccNum, txtDOB, txtFaxNum, txtFirstName, txtHPBNum, txtLastName, txtLinkedIn1, txtMedRec, txtPhNum, txtSSN, txtSrNum, txtVecType});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtEmailID, txtIMEINum, txtIPAdd, txtLicNum, txtLinkedIn, txtUniqueID});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblEINNum, lblLicNum, lblValIMEINum, lblValIPAdd});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {addIP, devType, emailID, fullFaceMulPics, imeiNum, licNum, linkedIn, uniqueID});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblValBANum, lblValBenNum, lblValFName, lblValFaxNum, lblValLName, lblValMedNum, lblValPhNum, lblValSSNNum, lblValSrNum});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void customvalidate(){
        
       
        
isFirstName = txtFirstName.getText().isEmpty();
//isDOB = txtDOB.getDateFormatString().isEmpty();

isLastName = txtLastName.getText().isEmpty();
isAddress = txtLinkedIn1.getText().isEmpty();
isPhNum = txtPhNum.getText().replaceAll("\\s+","").isEmpty();
isFaxNum = txtFaxNum.getText().replace("-","").replaceAll("\\s+","").isEmpty();
isEmailID = txtEmailID.getText().replaceAll("\\s+","").isEmpty();
isSSN = txtSSN.getText().replace("-","").replaceAll("\\s+","").isEmpty();
isMedRec = txtMedRec.getText().replaceAll("\\s+","").isEmpty();
isHPBNum = txtHPBNum.getText().replace("-","").replaceAll("\\s+","").isEmpty();
isBnkAccNum = txtBnkAccNum.getText().replaceAll("\\s+","").isEmpty();
isLicNum = txtLicNum.getText().replaceAll("\\s+","").isEmpty();
//isVecType = txtVecType.getSelectedItem().toString().isEmpty();
isSrNum = txtSrNum.getText().replaceAll("\\s+","").isEmpty();
isIMEINum = txtIMEINum.getText().replaceAll("\\s+","").isEmpty();
isLinkedIn = txtLinkedIn.getText().replaceAll("\\s+","").isEmpty();
isIPAdd = txtIPAdd.getText().replace(".","").isEmpty();
//isFaceRec = txtFaceRec.getText().isEmpty();
isimgUpload = imgUpload.getText().isEmpty();
isUniqueID = txtUniqueID.getText().replaceAll("\\s+","").replace("-","").isEmpty();
isIOSRadioBtn = iOSRadioBtn.isSelected();
isAndroidRadioButton = androidRadioButton.isSelected();
isWindowsRadioButton1 = windowsRadioButton1.isSelected();
isRadio = !(iOSRadioBtn.isSelected() || androidRadioButton.isSelected()|| windowsRadioButton1.isSelected());
JOptionPane.showMessageDialog(this, " isLastName : "+ isLastName + " isAddress : " + isAddress + " isPhNum : " + isPhNum + " isFaxNum : " + isFaxNum + " isEmailID : " + isEmailID + " isSSN : " + isSSN + " isMedRec : " + isMedRec + " isHPBNum : " + isHPBNum + " isBnkAccNum : " + isBnkAccNum + " isLicNum : " + isLicNum + " isVecType : " + isVecType + " isSrNum : " + isSrNum + " isIMEINum : " + isIMEINum + " isLinkedIn : " + isLinkedIn + " isIPAdd : " + isIPAdd + " isFaceRec : " + isFaceRec + " isimgUpload : " + isimgUpload + " isUniqueID : " + isUniqueID  + " isIOSRadioBtn : " + isIOSRadioBtn + " isAndroidRadioButton : " + isAndroidRadioButton + " isWindowsRadioButton1 : " + isWindowsRadioButton1 + " isRadio : " + isRadio);
        
    }
    
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
//        dataValidation();

       boolean isInValid = false;
       //customvalidate();
       if(
               //txtFirstName.getText().isEmpty()|| txtDOB.getDateFormatString().isEmpty()
               txtFirstName.getText().isEmpty()
|| txtLastName.getText().isEmpty()
|| txtLinkedIn1.getText().isEmpty()
|| txtPhNum.getText().replaceAll("\\s+","").isEmpty()
|| txtFaxNum.getText().replace("-","").replaceAll("\\s+","").isEmpty()
|| txtEmailID.getText().replaceAll("\\s+","").isEmpty()
|| txtSSN.getText().replace("-","").replaceAll("\\s+","").isEmpty()
|| txtMedRec.getText().replaceAll("\\s+","").isEmpty()
|| txtHPBNum.getText().replace("-","").replaceAll("\\s+","").isEmpty()
|| txtBnkAccNum.getText().replaceAll("\\s+","").isEmpty()
|| txtLicNum.getText().replaceAll("\\s+","").isEmpty()
|| txtSrNum.getText().replaceAll("\\s+","").isEmpty()
|| txtIMEINum.getText().replaceAll("\\s+","").isEmpty()
|| txtLinkedIn.getText().replaceAll("\\s+","").isEmpty()
|| txtIPAdd.getText().replace(".","").isEmpty()
//|| txtFaceRec.getText().isEmpty()
|| imgUpload.getText().isEmpty()
|| txtUniqueID.getText().replaceAll("\\s+","").replace("-","").isEmpty()
 || !(iOSRadioBtn.isSelected() || androidRadioButton.isSelected()|| windowsRadioButton1.isSelected())


               //|| iOSRadioBtn.isEnabled(false)
               ) 
               {
           
      JOptionPane.showMessageDialog(this, "Incorrect Information"); 
       }
       else
       {
        product.setFstName(txtFirstName.getText());
        product.setLstName(txtLastName.getText());
        product.setGeoData(txtLinkedIn1.getText());
        product.setDob(txtDOB.getDateFormatString().toString());
        product.setPhNum(txtPhNum.getText());
        product.setFaxNum(txtFaxNum.getText());
        product.setEmailId(txtEmailID.getText());
        product.setSsn(txtSSN.getText());
        product.setMedRec(txtMedRec.getText());
        product.setHpbNum(txtHPBNum.getText());
        product.setBankAccNum(txtBnkAccNum.getText());
        product.setLicNum(txtLicNum.getText());
        product.setVecType((String) txtVecType.getSelectedItem());
        product.setSrNum(txtSrNum.getText());
        //product.setDevType(txtDevType.()); if condition needs to be checked for radio btns
        product.setDevSrNum(txtIMEINum.getText());
        product.setLinkedIn(txtLinkedIn.getText());
        product.setIpAdd(txtIPAdd.getText());
        //product.setBioMetrics(txtFaceRec.getText());
        product.setImg(imgUpload.getIcon());
        product.setUniqueID(txtUniqueID.getText());
        product.setDevType(product.getDevType());
        product.setAndRBtn(androidRadioButton.isSelected());
        product.setIOSRBtn(iOSRadioBtn.isSelected());
        product.setWinRBtn(windowsRadioButton1.isSelected());
        //.setText(product.getDevType());
                //windowsRadioButton1.setText(product.getDevType());
           
        
        
        product.setBankAccNum(txtBnkAccNum.getText());

        JOptionPane.showMessageDialog(this, "Product Information Saved Successfully");
            //if(fstName.equals("")) {
//JOptionPane.showMessageDialog(null, "All fields are mandatory.");
       }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
//        char fName = evt.getKeyChar();
//        if(Character.isDigit(fName)){
//            txtFirstName.setEditable(false);//            
//        }
//        else
//        {
//            txtFirstName.setEditable(true);
//            
//        }
    
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void txtFirstNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirstNameKeyTyped
        // TODO add your handling code here:
         char f = evt.getKeyChar();
         //Character.is
        if(Character.isAlphabetic(f)||Character.isISOControl(f)|| f == KeyEvent.VK_SPACE){
            txtFirstName.setEditable(true);
            lblValFName.setText("");
            }
        else
        {
            txtFirstName.setEditable(false);
            lblValFName.setText("Only Letters Are Allowed");
            
            }
    }//GEN-LAST:event_txtFirstNameKeyTyped

    private void txtVecTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVecTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVecTypeActionPerformed

    private void txtIPAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIPAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIPAddActionPerformed

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void txtLastNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLastNameKeyTyped
        // TODO add your handling code here:
        char l = evt.getKeyChar();
         //Character.is
        if(Character.isAlphabetic(l)||Character.isISOControl(l)|| l == KeyEvent.VK_SPACE){
            txtLastName.setEditable(true);
            lblValLName.setText("");
            }
        else
        {
            txtLastName.setEditable(false);
            lblValLName.setText("Only Letters Are Allowed");
            
            }
    }//GEN-LAST:event_txtLastNameKeyTyped

    private void txtPhNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhNumActionPerformed
        // TODO add your handling code here:
//        char d = evt.getKeyChar();
//         //Character.is
//        if(Character.isDigit(d)||Character.isISOControl(d)){
//            phNum.setEditable(true);
//            lblValPhNum.setText("");
//            }
//        else
//        {
//            phNum.setEditable(false);
//            lblValPhNum.setText("Please enter 10 digit number");
//            
//            }
    }//GEN-LAST:event_txtPhNumActionPerformed

    private void txtFaxNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFaxNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFaxNumActionPerformed

    private void txtSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSSNActionPerformed

    private void txtBnkAccNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBnkAccNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBnkAccNumActionPerformed

    private void txtHPBNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHPBNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHPBNumActionPerformed

    private void txtMedRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedRecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedRecActionPerformed

    private void txtLicNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLicNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLicNumActionPerformed

    private void txtUniqueIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUniqueIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUniqueIDActionPerformed

    private void txtIMEINumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIMEINumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIMEINumActionPerformed

    private void txtEmailIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailIDActionPerformed

    private void txtSrNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSrNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSrNumActionPerformed

    private void txtLinkedInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLinkedInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLinkedInActionPerformed

    private void uploadImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadImgActionPerformed
        // TODO add your handling code here:
      JFileChooser upload = new JFileChooser();
    upload.showOpenDialog(null);
    File nFile = upload.getSelectedFile();
    String filename = nFile.getName();
    //uploadImg.setText(filename);
    try {
        ImageIcon myImgs=new ImageIcon(scaleImage(120, 120, ImageIO.read(new File(nFile.getAbsolutePath()))));//get the image from file chooser and scale it to match JLabel size
        imgUpload.setIcon(myImgs);
        imgUpload.setText("Success");
    } catch (Exception exptn) {
        exptn.printStackTrace();
    }
    }
    public static BufferedImage scaleImage(int width, int height, BufferedImage img) throws Exception {
    BufferedImage bufImg;
    bufImg = new BufferedImage(width, height, BufferedImage.TRANSLUCENT);
    Graphics2D g2d = (Graphics2D) bufImg.createGraphics();
    g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
    g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY));
    g2d.drawImage(img, 0, 0, width, height, null);
    g2d.dispose();
    return bufImg;
    
        
    }//GEN-LAST:event_uploadImgActionPerformed

    private void txtPhNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhNumKeyTyped
        // TODO add your handling code here:
        char d = evt.getKeyChar();
         //Character.is
        if(Character.isDigit(d)||Character.isISOControl(d)){
           lblValPhNum.setText("");
            }
        else
        {
            lblValPhNum.setText("Please Enter 10 Digit Number");
            
            }
    }//GEN-LAST:event_txtPhNumKeyTyped

    private void txtFaxNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFaxNumKeyTyped
        // TODO add your handling code here:
        char f = evt.getKeyChar();
         
        if(Character.isDigit(f)||Character.isISOControl(f)){
           lblValFaxNum.setText("");
            }
        else
        {
            lblValFaxNum.setText("Please Enter 10 Digit FAX Number");
            
            }
    }//GEN-LAST:event_txtFaxNumKeyTyped

    private void txtSSNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSSNKeyTyped
        // TODO add your handling code here:
        char s = evt.getKeyChar();
         
        if(Character.isDigit(s)||Character.isISOControl(s)){
           lblValSSNNum.setText("");
            }
        else
        {
            lblValSSNNum.setText("Please Enter 9 Digit SSN Number");
            
            }
    }//GEN-LAST:event_txtSSNKeyTyped

    private void txtBnkAccNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBnkAccNumKeyTyped
        // TODO add your handling code here:
        char b = evt.getKeyChar();
         
        if((Character.isDigit(b)||Character.isISOControl(b))){
           lblValBANum.setText("");
            }
        else
        {
            lblValBANum.setText("Please Enter 12 Digit Bank Number");
            
            }
    }//GEN-LAST:event_txtBnkAccNumKeyTyped

    private void txtHPBNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHPBNumKeyTyped
        // TODO add your handling code here:
        char e = evt.getKeyChar();
         
        if((Character.isDigit(e)||Character.isISOControl(e))){
           lblValBenNum.setText("");
            }
        else
        {
            lblValBenNum.setText("Please Enter 11 Digit Beneficiary Number");
            
            }
        
    }//GEN-LAST:event_txtHPBNumKeyTyped

    private void txtSrNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSrNumKeyTyped
        // TODO add your handling code here:
        char s = evt.getKeyChar();
         
        if((Character.isDigit(s)||Character.isISOControl(s))){
           lblValSrNum.setText("");
            }
        else
        {
            lblValSrNum.setText("Please Enter Valid Vehicle Number");
            
            }
    }//GEN-LAST:event_txtSrNumKeyTyped

    private void txtMedRecKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMedRecKeyTyped
        // TODO add your handling code here:
        char m = evt.getKeyChar();
         
        if((Character.isDigit(m)||Character.isISOControl(m))){
           lblValMedNum.setText("");
            }
        else
        {
            lblValMedNum.setText("Please Enter Valid Medical Record Number");
            
            }
    }//GEN-LAST:event_txtMedRecKeyTyped

    private void txtIMEINumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIMEINumKeyTyped
        // TODO add your handling code here:
        char i = evt.getKeyChar();
         
        if((Character.isDigit(i)||Character.isISOControl(i))){
           lblValIMEINum.setText("");
            }
        else
        {
            lblValIMEINum.setText("Please Enter Valid IMEI Number");
            
            }
    }//GEN-LAST:event_txtIMEINumKeyTyped

    private void txtIPAddKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIPAddKeyTyped
        // TODO add your handling code here:
        char p = evt.getKeyChar();
         
        if((Character.isDigit(p)||Character.isISOControl(p))){
           lblValIPAdd.setText("");
            }
        else
        {
            lblValIPAdd.setText("Please Enter Valid IP Address");
            
            }
    }//GEN-LAST:event_txtIPAddKeyTyped

    private void txtUniqueIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUniqueIDKeyTyped
        // TODO add your handling code here:
        char n = evt.getKeyChar();
         
        if((Character.isDigit(n)||Character.isISOControl(n))){
           lblEINNum.setText("");
            }
        else
        {
            lblEINNum.setText("Please Enter Valid EIN Number");
            
            }
    }//GEN-LAST:event_txtUniqueIDKeyTyped

    private void txtLicNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLicNumKeyTyped
        // TODO add your handling code here:
        char g = evt.getKeyChar();
         
        if((Character.isDigit(g)||Character.isISOControl(g))){
           lblLicNum.setText("");
            }
        else
        {
            lblLicNum.setText("Please Enter Valid License Number");
            
            }
    }//GEN-LAST:event_txtLicNumKeyTyped

    private void iOSRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iOSRadioBtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_iOSRadioBtnActionPerformed

    private void txtLinkedIn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLinkedIn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLinkedIn1ActionPerformed
    
    
    public static void customValidate(){
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addIP;
    private javax.swing.JLabel address;
    private javax.swing.JRadioButton androidRadioButton;
    private javax.swing.JLabel bnkAccNum;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel devType;
    private javax.swing.JLabel dob;
    private javax.swing.JLabel emailID;
    private javax.swing.JLabel faxNum;
    private javax.swing.JLabel frstName;
    private javax.swing.JLabel fullFaceMulPics;
    private javax.swing.JLabel hlthBenNum;
    private javax.swing.JRadioButton iOSRadioBtn;
    private javax.swing.JLabel imeiNum;
    private javax.swing.JLabel imgUpload;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEINNum;
    private javax.swing.JLabel lblLicNum;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblValAdd;
    private javax.swing.JLabel lblValBANum;
    private javax.swing.JLabel lblValBenNum;
    private javax.swing.JLabel lblValFName;
    private javax.swing.JLabel lblValFaxNum;
    private javax.swing.JLabel lblValIMEINum;
    private javax.swing.JLabel lblValIPAdd;
    private javax.swing.JLabel lblValLName;
    private javax.swing.JLabel lblValMedNum;
    private javax.swing.JLabel lblValPhNum;
    private javax.swing.JLabel lblValSSNNum;
    private javax.swing.JLabel lblValSrNum;
    private javax.swing.JLabel licNum;
    private javax.swing.JLabel linkedIn;
    private javax.swing.JLabel lstName;
    private javax.swing.JLabel medRecNum;
    private javax.swing.JLabel phNum;
    private javax.swing.JLabel ssnNum;
    private javax.swing.JFormattedTextField txtBnkAccNum;
    private com.toedter.calendar.JDateChooser txtDOB;
    private javax.swing.JFormattedTextField txtEmailID;
    private javax.swing.JFormattedTextField txtFaxNum;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JFormattedTextField txtHPBNum;
    private javax.swing.JFormattedTextField txtIMEINum;
    private javax.swing.JFormattedTextField txtIPAdd;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JFormattedTextField txtLicNum;
    private javax.swing.JFormattedTextField txtLinkedIn;
    private javax.swing.JFormattedTextField txtLinkedIn1;
    private javax.swing.JFormattedTextField txtMedRec;
    private javax.swing.JFormattedTextField txtPhNum;
    private javax.swing.JFormattedTextField txtSSN;
    private javax.swing.JFormattedTextField txtSrNum;
    private javax.swing.JFormattedTextField txtUniqueID;
    private javax.swing.JComboBox<String> txtVecType;
    private javax.swing.JLabel uniqueID;
    private javax.swing.JButton uploadImg;
    private javax.swing.JLabel vecSrNum;
    private javax.swing.JLabel vecType;
    private javax.swing.JRadioButton windowsRadioButton1;
    // End of variables declaration//GEN-END:variables

//    private void dataValidation() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }
}
