/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.Set;
import model.Product;

/**
 *
 * @author Bhabani
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    
    Product product;
    
    public ViewJPanel(Product product) {
        initComponents();
        
        this.product = product;
        displayProduct();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtEmailID = new javax.swing.JFormattedTextField();
        txtDOB = new com.toedter.calendar.JDateChooser();
        lblValFName = new javax.swing.JLabel();
        lblValLName = new javax.swing.JLabel();
        txtSrNum = new javax.swing.JFormattedTextField();
        lblValAdd = new javax.swing.JLabel();
        txtLinkedIn = new javax.swing.JFormattedTextField();
        imgUpload = new javax.swing.JLabel();
        lblValBANum = new javax.swing.JLabel();
        fullFaceMulPics = new javax.swing.JLabel();
        lblValFaxNum = new javax.swing.JLabel();
        linkedIn = new javax.swing.JLabel();
        lblValSSNNum = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblValBenNum = new javax.swing.JLabel();
        lblValSrNum = new javax.swing.JLabel();
        frstName = new javax.swing.JLabel();
        lblValMedNum = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        lblValIMEINum = new javax.swing.JLabel();
        dob = new javax.swing.JLabel();
        phNum = new javax.swing.JLabel();
        faxNum = new javax.swing.JLabel();
        bnkAccNum = new javax.swing.JLabel();
        devType = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        vecSrNum = new javax.swing.JLabel();
        vecType = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        licNum = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lblValIPAdd = new javax.swing.JLabel();
        lblEINNum = new javax.swing.JLabel();
        lblLicNum = new javax.swing.JLabel();
        lblValPhNum = new javax.swing.JLabel();
        ssnNum = new javax.swing.JLabel();
        emailID = new javax.swing.JLabel();
        addIP = new javax.swing.JLabel();
        medRecNum = new javax.swing.JLabel();
        imeiNum = new javax.swing.JLabel();
        hlthBenNum = new javax.swing.JLabel();
        uniqueID = new javax.swing.JLabel();
        lstName = new javax.swing.JLabel();
        txtVecType = new javax.swing.JComboBox<>();
        txtIPAdd = new javax.swing.JFormattedTextField();
        txtPhNum = new javax.swing.JFormattedTextField();
        txtFaxNum = new javax.swing.JFormattedTextField();
        txtSSN = new javax.swing.JFormattedTextField();
        txtBnkAccNum = new javax.swing.JFormattedTextField();
        txtHPBNum = new javax.swing.JFormattedTextField();
        txtMedRec = new javax.swing.JFormattedTextField();
        txtLicNum = new javax.swing.JFormattedTextField();
        txtUniqueID = new javax.swing.JFormattedTextField();
        txtIMEINum = new javax.swing.JFormattedTextField();
        iOSRadioBtn = new javax.swing.JRadioButton();
        androidRadioButton = new javax.swing.JRadioButton();
        windowsRadioButton1 = new javax.swing.JRadioButton();

        setLayout(new java.awt.BorderLayout());

        try {
            txtEmailID.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("******************************************************")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblValFName.setForeground(new java.awt.Color(255, 51, 0));

        lblValLName.setForeground(new java.awt.Color(255, 51, 0));

        try {
            txtSrNum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("*******")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblValAdd.setForeground(new java.awt.Color(255, 51, 0));

        try {
            txtLinkedIn.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("*****************************")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblValBANum.setForeground(new java.awt.Color(255, 51, 0));

        fullFaceMulPics.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        fullFaceMulPics.setText("Full Face Multiple Photos:");

        lblValFaxNum.setForeground(new java.awt.Color(255, 51, 0));

        linkedIn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        linkedIn.setText("LinkedIn:");

        lblValSSNNum.setForeground(new java.awt.Color(255, 51, 0));

        lblTitle.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create Profile");

        lblValBenNum.setForeground(new java.awt.Color(255, 51, 0));

        lblValSrNum.setForeground(new java.awt.Color(255, 51, 0));

        frstName.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        frstName.setText("First Name:");
        frstName.setAlignmentY(0.1F);

        lblValMedNum.setForeground(new java.awt.Color(255, 51, 0));

        address.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        address.setText("Address:");
        address.setAlignmentY(0.1F);

        lblValIMEINum.setForeground(new java.awt.Color(255, 51, 0));

        dob.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        dob.setText("Date of Birth:");
        dob.setAlignmentY(0.1F);

        phNum.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        phNum.setText("Phone Number:");
        phNum.setAlignmentY(0.1F);

        faxNum.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        faxNum.setText("Fax Number:");
        faxNum.setAlignmentY(0.1F);

        bnkAccNum.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        bnkAccNum.setText("Bank account Number:");
        bnkAccNum.setAlignmentY(0.1F);

        devType.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        devType.setText("Device Type:");

        txtFirstName.setAlignmentY(0.1F);
        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });

        vecSrNum.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        vecSrNum.setText("Vehicle Serial Number:");

        vecType.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        vecType.setText("Vehicle Type:");

        txtLastName.setAlignmentY(0.1F);

        licNum.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        licNum.setText("Licence Number:");

        txtAddress.setAlignmentY(0.1F);

        lblValIPAdd.setForeground(new java.awt.Color(255, 51, 0));

        lblEINNum.setForeground(new java.awt.Color(255, 51, 0));

        lblLicNum.setForeground(new java.awt.Color(255, 51, 0));

        lblValPhNum.setForeground(new java.awt.Color(255, 51, 0));

        ssnNum.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        ssnNum.setText("SSN Number:");
        ssnNum.setAlignmentY(0.1F);

        emailID.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        emailID.setText("Email ID:");
        emailID.setAlignmentY(0.1F);

        addIP.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        addIP.setText("IP Address:");

        medRecNum.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        medRecNum.setText("Medical Record Number:");

        imeiNum.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        imeiNum.setText("IMEI Number:");

        hlthBenNum.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        hlthBenNum.setText("Health plan beneficiary Number:");
        hlthBenNum.setAlignmentY(0.1F);

        uniqueID.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        uniqueID.setText("EIN Number:");

        lstName.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        lstName.setText("Last Name:");
        lstName.setAlignmentY(0.1F);

        txtVecType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Car", "Bike" }));

        try {
            txtIPAdd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###.###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtPhNum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtFaxNum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtSSN.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtBnkAccNum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("############")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtHPBNum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtMedRec.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtLicNum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("AAAAAAAAA")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtUniqueID.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##-#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtIMEINum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###############")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        iOSRadioBtn.setText("iOS");
        iOSRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iOSRadioBtnActionPerformed(evt);
            }
        });

        androidRadioButton.setText("Android");

        windowsRadioButton1.setText("Windows");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(medRecNum)
                    .addComponent(emailID))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValLName, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValFName, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValBenNum, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValMedNum, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(lblValSrNum, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(frstName, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(address, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(dob, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(phNum, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(faxNum, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(bnkAccNum, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(devType, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(vecSrNum, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(vecType, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ssnNum, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(hlthBenNum, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lstName, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtHPBNum, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtVecType, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtSrNum, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(iOSRadioBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(androidRadioButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(windowsRadioButton1))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addComponent(txtMedRec, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addComponent(txtEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(5, 5, 5)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPhNum, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtFaxNum, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtBnkAccNum, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblValBANum, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblValSSNNum, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblValFaxNum, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblValPhNum, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(25, 25, 25)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(linkedIn)
                                .addComponent(imeiNum)
                                .addComponent(licNum)
                                .addComponent(uniqueID)
                                .addComponent(fullFaceMulPics)
                                .addComponent(addIP))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtIPAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtIMEINum, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtUniqueID, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtLicNum, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblEINNum, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblLicNum, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(imgUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(364, 364, 364)
                            .addComponent(lblValAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(860, 860, 860)
                            .addComponent(lblValIPAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(864, 864, 864)
                            .addComponent(lblValIMEINum, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(286, 286, 286)
                            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(22, 22, 22)))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAddress, txtBnkAccNum, txtDOB, txtEmailID, txtFaxNum, txtFirstName, txtHPBNum, txtLastName, txtMedRec, txtPhNum, txtSSN, txtSrNum, txtVecType});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblValAdd, lblValBANum, lblValBenNum, lblValFName, lblValFaxNum, lblValLName, lblValMedNum, lblValPhNum, lblValSSNNum, lblValSrNum});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtIMEINum, txtIPAdd, txtLicNum, txtLinkedIn, txtUniqueID});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(lblValFName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblValLName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(237, 237, 237)
                .addComponent(lblValBenNum, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(medRecNum, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailID))
                    .addComponent(lblValSrNum, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblValMedNum, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblTitle)
                    .addGap(44, 44, 44)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(frstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblValAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblValIMEINum, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(imeiNum, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtIMEINum, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(linkedIn))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(txtLinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(5, 5, 5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(addIP, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtIPAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblValIPAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(37, 37, 37)
                                    .addComponent(fullFaceMulPics)
                                    .addGap(53, 53, 53)
                                    .addComponent(uniqueID, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(licNum))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(imgUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtUniqueID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(14, 14, 14)
                                            .addComponent(txtLicNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(lblEINNum, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(lblLicNum, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGap(126, 126, 126))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lstName))
                            .addGap(8, 8, 8)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 0, 0)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(2, 2, 2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(phNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPhNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblValPhNum, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(faxNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtFaxNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblValFaxNum, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ssnNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblValSSNNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bnkAccNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtBnkAccNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblValBANum, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(hlthBenNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtHPBNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(1, 1, 1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(vecType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtVecType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(vecSrNum)
                                .addComponent(txtSrNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(6, 6, 6)
                            .addComponent(txtMedRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(devType)
                                .addComponent(iOSRadioBtn)
                                .addComponent(androidRadioButton)
                                .addComponent(windowsRadioButton1))
                            .addContainerGap()))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtAddress, txtBnkAccNum, txtDOB, txtEmailID, txtFaxNum, txtFirstName, txtHPBNum, txtLastName, txtMedRec, txtPhNum, txtSSN, txtSrNum, txtVecType});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblValAdd, lblValBANum, lblValBenNum, lblValFName, lblValFaxNum, lblValLName, lblValMedNum, lblValPhNum, lblValSSNNum});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtIMEINum, txtIPAdd, txtLicNum, txtLinkedIn, txtUniqueID});

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void iOSRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iOSRadioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iOSRadioBtnActionPerformed

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addIP;
    private javax.swing.JLabel address;
    private javax.swing.JRadioButton androidRadioButton;
    private javax.swing.JLabel bnkAccNum;
    private javax.swing.JLabel devType;
    private javax.swing.JLabel dob;
    private javax.swing.JLabel emailID;
    private javax.swing.JLabel faxNum;
    private javax.swing.JLabel frstName;
    private javax.swing.JLabel fullFaceMulPics;
    private javax.swing.JLabel hlthBenNum;
    private javax.swing.JRadioButton iOSRadioBtn;
    private javax.swing.JLabel imeiNum;
    private javax.swing.JLabel imgUpload;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEINNum;
    private javax.swing.JLabel lblLicNum;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblValAdd;
    private javax.swing.JLabel lblValBANum;
    private javax.swing.JLabel lblValBenNum;
    private javax.swing.JLabel lblValFName;
    private javax.swing.JLabel lblValFaxNum;
    private javax.swing.JLabel lblValIMEINum;
    private javax.swing.JLabel lblValIPAdd;
    private javax.swing.JLabel lblValLName;
    private javax.swing.JLabel lblValMedNum;
    private javax.swing.JLabel lblValPhNum;
    private javax.swing.JLabel lblValSSNNum;
    private javax.swing.JLabel lblValSrNum;
    private javax.swing.JLabel licNum;
    private javax.swing.JLabel linkedIn;
    private javax.swing.JLabel lstName;
    private javax.swing.JLabel medRecNum;
    private javax.swing.JLabel phNum;
    private javax.swing.JLabel ssnNum;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JFormattedTextField txtBnkAccNum;
    private com.toedter.calendar.JDateChooser txtDOB;
    private javax.swing.JFormattedTextField txtEmailID;
    private javax.swing.JFormattedTextField txtFaxNum;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JFormattedTextField txtHPBNum;
    private javax.swing.JFormattedTextField txtIMEINum;
    private javax.swing.JFormattedTextField txtIPAdd;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JFormattedTextField txtLicNum;
    private javax.swing.JFormattedTextField txtLinkedIn;
    private javax.swing.JFormattedTextField txtMedRec;
    private javax.swing.JFormattedTextField txtPhNum;
    private javax.swing.JFormattedTextField txtSSN;
    private javax.swing.JFormattedTextField txtSrNum;
    private javax.swing.JFormattedTextField txtUniqueID;
    private javax.swing.JComboBox<String> txtVecType;
    private javax.swing.JLabel uniqueID;
    private javax.swing.JLabel vecSrNum;
    private javax.swing.JLabel vecType;
    private javax.swing.JRadioButton windowsRadioButton1;
    // End of variables declaration//GEN-END:variables

//    private void txtFirstNameKeyPressed(java.awt.event.KeyEvent evt) {                                        
//                
//        char c = evt.getKeyChar();
//        if(Character.isDigit(c)){
//        txtFirstName.setEditable(false);
//        lblFirstNameValidation.setText("Please enter letters only!");
//        }
//        else
//        {
//        txtFirstName.setEditable(true);
//        lblFirstNameValidation.setText(""); // To disable the warnings once user feed correct character
//        }
//    }
    private void displayProduct() {
        		txtFirstName.setText(product.getFstName());
        txtLastName.setText(product.getLstName());
        txtAddress.setText(product.getGeoData());
        txtDOB.setDateFormatString(product.getDob());
        txtPhNum.setText(product.getPhNum());
        txtFaxNum.setText(product.getFaxNum());
        txtEmailID.setText(product.getEmailId());
        txtSSN.setText(product.getSsn());
        txtMedRec.setText(product.getMedRec());
        txtHPBNum.setText(product.getHpbNum());
        txtBnkAccNum.setText(product.getBankAccNum());
        txtLicNum.setText(product.getLicNum());
        txtVecType.setSelectedItem(product.getVecType());
        txtSrNum.setText(product.getSrNum());
		txtIMEINum.setText(product.getDevSrNum());
		txtLinkedIn.setText(product.getLinkedIn());
		txtIPAdd.setText(product.getIpAdd());
		imgUpload.setIcon(product.getImg());
		txtUniqueID.setText(product.getUniqueID());
                iOSRadioBtn.setEnabled(product.getIOSRBtn());
                androidRadioButton.setEnabled(product.getAndRBtn());
                windowsRadioButton1.setEnabled(product.getWinRBtn());
//        txtFirstName.setText(product.getFstName());
//        txtLastName.setText(product.getLstName());
//        txtAddress.setText(product.getGeoData());
//        txtVecType.setSelectedItem(product.getVecType());
//        iOSRadioBtn.setText(product.getDevType());
//        windowsRadioButton1.setText(product.getDevType());
//        androidRadioButton.setText(product.getDevType());
//        txtAddress.setText(product.getGeoData());
//        txtAddress.setText(product.getGeoData());
//        txtAddress.setText(product.getGeoData());
//        txtAddress.setText(product.getGeoData());
//        txtAddress.setText(product.getGeoData());
//        txtAddress.setText(product.getGeoData());
//        txtAddress.setText(product.getGeoData());
//        txtAddress.setText(product.getGeoData());
//        txtAddress.setText(product.getGeoData());
        //txtBnkAccNum.setText(product.getBankAccNum());
        //txtDOB.setText(product.getDob());
        //txt

//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
